main.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import config

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config.from_object(config) # config 에서 가져온 파일을 사용합니다.

    db.init_app(app) # SQLAlchemy 객체를 app 객체와 이어줍니다.
    Migrate().init_app(app, db)

    from views import main_view, store_detail_view
    from models import models
    app.register_blueprint(main_view.bp)
    app.register_blueprint(store_detail_view.bp)

    app.secret_key = "seeeeeeeeeeeecret"
    app.config['SESSION_TYPE'] = 'filesystem'

    '''
    세션을 사용하기 위해선, 보안을 위해 세션을 암호화해야 합니다.

    암호화 하는 과정에서 사용하는 비밀 키가 app.secret_key 입니다.

    따라서, 실제 서버를 사용하기 위해선 github 같은 곳에 secret_key를 절대!!! 올려선 안 됩니다.
    이후 여러분들이 서버를 실제 배포 (Apache나 Nginx)를 사용할 때는 파일을 분리하거나, 환경 변수를 설정하는 방식으로
    secret_key가 절대 깃에 노출되지 않도록 해야 합니다.

    그렇다면 SESSION_TYPE = 'filesystem'은 무슨 역할일까요?
    
    세션 정보를 별도의 파일로 뺄 수도 있고, DB에 저장할 수도 있습니다. (flask 에서는 sqlalchemy, redis/mongodb 같은 설정이 가능합니다.)
    그런데 세션을 DB로 관리하기 위해선, 별도의 구조를 만들어야겠죠?
    현재 상황에선 그런 부분을 피하기 위해 filesystem으로 관리합니다.
    '''
    
    return app

if __name__ == "__main__":
    create_app().run(debug=True, port=3333)

views/main_view.py
'''
view는 우리 눈에 보이는 부분을 관리합니다.

지난 시간에 작업했을 때는 view를 여러 파일로 분리하지 않았는데, 상황에 따라 파일을 분리할 수 있습니다.
그러면 어떻게 관리하냐고요?

어차피 각 파일마다 별도의 Blueprint를 만들테니, __init__.py에서 전부 import 하고
각각 다 register_blueprint를 활용해서 이어줍니다.

추가로, 코드를 보다보면 query를 사용한 것이 많은데, 이를 활용하면 SQL 구문을 직접 사용하지 않고
ORM을 통해 간접적으로 db에 작업 명령을 내릴 수 있습니다.
'''


from flask import Blueprint, render_template, request, url_for, session, redirect, flash
from models.models import *
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def home():
    store_list = rabbitStore.query.order_by(rabbitStore.name.asc())
    return render_template('main.html', store_list=store_list)

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'GET':
        return render_template('register.html')
    elif request.method == 'POST':
        # 회원가입 과정을 거쳐야겠다!
        # 만약에 같은 아이디가 있으면 어떡해?
        user = rabbitUser.query.filter_by(id=request.form['user_id']).first()
        if not user:
            password = generate_password_hash(request.form['password']) #비밀번호 암호화!
            user = rabbitUser(id=request.form['user_id'], password=password,
            nickname=request.form['nickname'], telephone=request.form['telephone'])
        
            db.session.add(user)
            db.session.commit()
            
            #flash를 하면 바로 띄우느것이 아니라 render_template이 될때까지 쌓임. 리스트로 저장되어있음!
            flash("회원가입이 완료되었습니다")

            return redirect(url_for('main.home')) #main = blueprint 지정한 name
        else:
            flash("이미 가입된 아이디입니다.")
            return redirect(url_for('main.register'))

#render template -> 페이지 주소는 안 바뀌는데 그냥 html만 띄우는거
#redirect -> 페이지 주소까지 바꿔버리는거
#POST -> 일반적으로 페이지를 띄으지 않는다 -> 즉, redirect로 보내는게 맞음
#GET인데도 다른 페이지를 띄워야 할 피료악 있다면 redirect로 보내는게 맞음

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        id          = request.form['user_id']
        password    = request.form['password']

        user_data = rabbitUser.query.filter_by(id=id).first()

        if not user_data:
            flash("없는 아이디입니다.")
            return redirect(url_for('main.login'))
        elif not check_password_hash(user_data.password, password):
            flash("비밀번호가 틀렸습니다.") 
            return redirect(url_for('main.login'))
        else:
            session.clear()
            session['user_id'] = id
            session['nickname'] = user_data.nickname

            flash(f"{user_data.nickname}님, 환영합니다!")
            return redirect(url_for('main.home'))

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.home'))

views/oauth.py
import requests
from flask import Blueprint, render_template, request, url_for, session, redirect, flash
from models.models import *
from key.kakao_client import kakao_client_id
from werkzeug.security import check_password_hash, generate_password_hash
bp = Blueprint("kakao", __name__, url_prefix="/oauth/kakao")

@bp.route("/")
def kakao_sign_in():
    client_id = kakao_client_id
    redirect_uri = "http://www.localhost:3333/oauth/kakao/callback"
    kakao_oauthurl =  f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    return redirect(kakao_oauthurl)

@bp.route("/callback")
def callback():
    code = request.args["code"]
    client_id = kakao_client_id
    redirect_uri = "http://www.localhost:3333/oauth/kakao/callback"
    kakao_oauthurl =  f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"

    token_request = requests.get(kakao_oauthurl)
    token_json = token_request.json()

    if "error" in token_json:
        error = token_json["error"]
        flash("에러가 발생했습니다.")
        return redirect(url_for("main.home"))

    access_token = token_json["access_token"]

    profile_request = requests.get(
        "https://kapi.kakao.com/v2/user/me", headers={"Authorization" : f"Bearer {access_token}"},
    )
    data = profile_request.json()

    kakao_account = data["kakao_account"]
    profile = kakao_account["profile"]
    nickname = profile["nickname"]
    email = kakao_account["email"]
    kakao_id = data["id"]

    user = rabbitUser.query.filter_by(id=email).first()

    if not user:
        new_user = rabbitUser(id=email, password=kakao_id, nickname=nickname)
        
        db.session.add(new_user)
        db.session.commit()

    session['user_id'] = email
    session['nickname'] = nickname

    flash(f'안녕하세요. {nickname}님!')
    return redirect(url_for('main.home'))

views/store_detail_view.py
from flask import Blueprint, render_template, request, url_for, session, redirect, flash
from models.models import *

bp = Blueprint('store_detail', __name__, url_prefix="/store")

# 가게의 정보를 출력하기 위한 부분이에요.
@bp.route('/<int:store_id>')
def store_detail(store_id):
    store_info = rabbitStore.query.filter_by(id=store_id).first()
    review_info = rabbitReview.query.filter_by(store_id=store_id).all()
    if not store_info:
        flash("잘못된 접근입니다.")
        return redirect(url_for('main.home'))
    
    rating_sum, average = 0, 0
    if review_info:
        for review in review_info:
            rating_sum += review.rating 
        average = rating_sum / len(review_info)

    return render_template("store_detail.html", store_info=store_info, review_info=review_info, avg=average)
    

# 리뷰 작성입니다.
# user_id, store_id, 나머지 두개을 어떤 식으로 받는지 잘 체크하세요.
@bp.route('/write_review/<int:store_id>', methods=('POST',))
def create_review(store_id):
    if 'user_id' not in session:
        flash("권한이 없습니다.")
        return redirect(url_for('main.home'))

    user_info = rabbitUser.query.filter_by(id=session['user_id']).first()
    if not user_info:
        flash("권한이 없습니다.")
        return redirect(url_for('main.home'))

    user_id = session['user_id']
    review_rating = request.form['star']
    review_content = request.form['review']

    review = rabbitReview(user_id=user_id, store_id=store_id, rating=review_rating, content=review_content)
    
    db.session.add(review)
    db.session.commit()

    flash("리뷰 업로드가 완료되었습니다!")
    return redirect(url_for("store_detail.store_detail", store_id=store_id))

# 리뷰 삭제입니다.
# 리뷰 삭제를 위해선 일단 이 리뷰가 해당 유저가 쓴게 맞는지,
# 이 리뷰가 그 가게의 리뷰가 맞는지 확인해야 합니다.
@bp.route('/delete_review/<int:review_id>')
def delete_review(review_id):
    if 'user_id' not in session:
        flash("권한이 없습니다.")
        return redirect(url_for('main.home'))

    user_info = rabbitUser.query.filter_by(id=session['user_id']).first()
    review_info = rabbitReview.query.filter_by(id=review_id).first()
    
    if not review_info:
        flash("잘못된 접근입니다.")
        return redirect(url_for('main.home'))

    if not user_info or review_info.user_id != session['user_id']:
        flash("권한이 없습니다.")
        return redirect(url_for('main.home'))

    db.session.delete(review_info)
    db.session.commit()

    flash("정상적으로 삭제 되었습니다.")

    store_info = rabbitStore.query.filter_by(id=review_info.store_id).first()
    return redirect(url_for("store_detail.store_detail", store_id=store_info.id))

# 마이 페이지라고 써있지만, 사실 그냥 개인정보 수정용이에요!
# 다만, 로그인을 한 유저만 접근할 수 있도록 해야겠죠?
@bp.route('/mypage', methods=('POST', 'GET'))
def update_info():
    pass

templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark border-bottom" style="background-color: #7979D3;">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">배달의 토끼</a>
        <button
            class="navbar-toggler ml-auto"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            
            <ul class="nav navbar-nav navbar-right">
                <!-- 네비게이션 바-->
                {% if session['user_id'] %}
                    <li class="nav-item">
                        <span class="nav-link" style="color: white;">안녕하세요! {{ session['nickname'] }} 님!</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.logout') }}">로그아웃</a>               
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.register') }}">회원가입</a>               
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.login') }}">로그인</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link
            rel="shortcut icon"
            href="{{ url_for('static', filename='favicon.ico') }}"
            type="image/x-icon"
        />
        <link
            rel="icon"
            href="{{ url_for('static', filename='favicon.ico') }}"
            type="image/x-icon"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='bootstrap.min.css') }}"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='my_styles.css') }}"
        />
        <!-- 각 html 페이지 타이틀  -->
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <!-- 부트스트랩 내비게이션 포함 -->
        {% include "_navbar.html" %}
        {% block content %}
        <div class="container my-3">
            <!-- flash로 보내는 신호 수신 -->
            {% for message in get_flashed_messages() %}
                <div class="alert alert-info">
                    {{ message }}
                </div>
            {% endfor %}
            <!-- 각 페이지의 내용이 들어감 -->
            {% block page_content %} {% endblock %}
        </div>
        {% endblock %}
    </body>
</html>

templates/login.html
{% extends "base.html" %}

{% block page_content %}
    <form action="{{ url_for('main.login') }}" method="post">
        <div class="form-group">
            <label for="user_id">아이디</label>
            <input class="form-control" type="text" name="user_id" id="user_id" placeholder="아이디 입력" >
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input class="form-control" name="password" type="password" placeholder="비밀번호 입력">
        </div>
        <input class="btn btn-primary" type="submit" value="로그인!">
        <a href="{{ url_for('kakao.kakao_sign_in') }}"><img src="../static/kakao_login_medium_narrow.png" /></a>
    </form>
{% endblock %}

templates/main.html
{% extends "base.html" %}

{% block title %}메인 페이지{% endblock %}

{% block page_content %}    
    {% if store_list %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ul class="list-group">
                    {% for store in store_list%}
                        <a href="/store/{{ store.id }}"><li class="list-group-item list-group-item-action">{{ store.name }}</li></a>
                    {% endfor %}
                </ul>                
            </div>
        </div>
    </div>
    {% else %}
    <p>가게가 없어요...</p>
    {% endif %}
{% endblock %}

templates/mypage.html
{% extends "base.html" %}

{% block title %}회원 정보 수정{% endblock %}

{% block page_content %}    
    {% if user_info %}
        <form action="{{ url_for('main.update_info') }}" method="post">
            <div class="form-group">
                <label for="nickname">닉네임</label>
                <input class="form-control" name="nickname" type="nickname" placeholder="닉네임 입력">
            </div>
            <div class="form-group">
                <label for="password">비밀번호 확인 (개인정보를 수정하기 위해선 비밀번호를 입력해야 합니다.)</label>
                <input class="form-control" name="password" type="password" placeholder="비밀번호 입력">
            </div>
            <input class="btn btn-primary" type="submit" value="로그인!">
        </form>
    {% endif %}
{% endblock %}

templates/register.html
{% extends "base.html" %} 

{% block page_content %}

<form action="{{ url_for('main.register') }}" method="post">
  <div class="form-group">
    <label for="user_id">아이디</label>
    <input
      class="form-control"
      type="text"
      name="user_id"
      id="user_id"
      placeholder="아이디 입력"
    />
  </div>
  <div class="form-group">
    <label for="password">비밀번호</label>
    <input
      class="form-control"
      name="password"
      type="password"
      placeholder="비밀번호 입력"
    />
  </div>
  <div class="form-group">
    <label for="nickname">닉네임</label>
    <input
      class="form-control"
      name="nickname"
      type="nickname"
      placeholder="닉네임 입력"
    />
  </div>
  <div class="form-group">
    <label for="telephone">전화번호</label>
    <input
      class="form-control"
      name="telephone"
      type="telephone"
      placeholder="전화번호 입력"
    />
  </div>
  <input class="btn btn-primary" type="submit" value="회원가입!" />
</form>
{% endblock %}

templates/store_detail.html
{% extends "base.html" %}

{% block page_content %}
    {% if store_info %}
        <table class="table table-hover table-condensed table-bordered">
            <tbody>
                <tr>
                    <th>가게 이름</th>
                    <th>{{ store_info.name }}</th>
                </tr>
            </tbody>
            <tbody>
                <tr>
                    <th>가게 위치</th>
                    <th>{{ store_info.location }}</th>
                </tr>
            </tbody>
            <tbody>
                <tr>
                    <th>가게 번호</th>
                    <th>{{ store_info.telephone }}</th>
                </tr>
            </tbody>
            <tbody>
                <tr>
                    <th>가게 별점</th>
                    <th>{{ store_info.rating }}</th>
                </tr>
            </tbody>
            <tbody>
                <tr>
                    <th>여는 시간</th>
                    <th>{{ store_info.open_time }}</th>
                </tr>
            </tbody>
            <tbody>
                <tr>
                    <th>닫는 시간</th>
                    <th>{{ store_info.close_time }}</th>
                </tr>
            </tbody>
            <tbody>
                <tr>
                    <th>찜</th>
                    <th>{{ store_info.stars }}</th>
                </tr>
            </tbody>
        </table>
        <hr/>

        {% if store_menu %}
            <h3>메뉴</h3>
            <ul>
            {% for menu in store_menu %}
                <li>{{ menu.food_name }} ({{ menu.price }} 원, {{ menu.description }})</li>
            {% endfor %}
            </ul>
        {% endif %}

        <h3>리뷰</h3>
        <h5>현재 {{ review_info|length }} 개의 리뷰가 있습니다.(평균: {{ avg }})</h5>
        {% for review in review_info %}
            <div>
                <!-- 리뷰가 3.0점 이상이라면 파란색을, 아니라면 빨간색을 표시함.-->
                {% if review.rating >= 3 %}
                    <p>
                        <span style="color: blue">{{ review.rating }}</span> {{review.content}}
                        {% if session['user_id'] == review.user_id %}
                            <a class="btn btn-danger btn-sm" href="{{ url_for('store_detail.delete_review', store_id=store_info.id, review_id=review.id) }}">삭제</a>
                        {% endif %}
                    </p>
                {% else %}
                    <p>
                        <span style="color: red">{{ review.rating }}</span> {{review.content}}
                        {% if session['user_id'] == review.user_id %}
                            <a class="btn btn-danger btn-sm" href="{{ url_for('store_detail.delete_review', store_id=store_info.id, review_id=review.id) }}">삭제</a>
                        {% endif %}
                    </p>
                {% endif %}
                
            </div>
        {% endfor %}
    
        <hr>
        {% if session['user_id'] %}
        <h3>리뷰 작성</h3>
        <form action="{{ url_for('store_detail.create_review', store_id=store_info.id) }}" method="post">
            <select name="star">
                <option value="1">1점</option>
                <option value="2">2점</option>
                <option value="3">3점</option>
                <option value="4">4점</option>
                <option value="5">5점</option>
            </select>
            <div class="form-group">
                <label for="review">리뷰</label>
                <input class="form-control" name="review" id="review" placeholder="리뷰를 작성해주세요."></input> 
            </div>
            <input class="btn btn-primary" type="submit" value="리뷰 올리기">
        </form>
        {% endif %}
    {% endif %}
    
{% endblock %}